version: '2'

services:
  web:
    build: .
    depends_on:
      # - redis
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/diaspora
    command: script/server

  postgres:
    image: 'kiasaki/alpine-postgres'
    environment:
      POSTGRES_USER: 'diaspora'
      POSTGRES_PASSWORD: 'diaspora'
    volumes:
      - /var/lib/postgresql/data

    #  redis:
    #    image: 'redis:alpine'
    #    command: redis-server
    #    ports:
    #      - '6379:6379'
    #    volumes:
    #      - /var/lib/redis/data
